#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    clawPot,        sensorPotentiometer)
#pragma config(Sensor, in2,    gyro,           sensorGyro)
#pragma config(Sensor, in3,    elevatorPot,    sensorPotentiometer)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           claw,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port3,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           backRight,     tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port5,           elevator,      tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port6,           liftLeft,      tmotorVex393_MC29, openLoop, encoderPort, I2C_5)
#pragma config(Motor,  port7,           liftRight,     tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_4)
#pragma config(Motor,  port8,           backLeft,      tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port9,           frontLeft,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1)
	{
		motor[frontRight] = motor[backRight] = vexRT[Ch2];
		motor[frontLeft] = motor[backLeft] = vexRT[Ch3];
		if(vexRT[Btn5U])
		{
			motor[liftLeft] = -127;
			motor[liftRight] = -127;
		}
		else if(vexRT[Btn6U])
		{
			motor[liftLeft] = 127;
			motor[liftRight] = 127;
		}
		else
		{
			motor[liftLeft] = 0;
			motor[liftRight] = 0;
		}
		if(vexRT[Btn5D])
		{
			motor[claw] = -127;
		}
		else if(vexRT[Btn6D])
		{
			motor[claw] = 127;
		}
		else
		{
			motor[claw] = 0;
		}
		if(vexRT[Btn7D])
		{
			motor[elevator] = -127;
		}
		else if(vexRT[Btn8D])
		{
			motor[elevator] = 127;
		}
		else
		{
			motor[elevator] = 0;
		}

	}
}
