#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    clawPot,        sensorPotentiometer)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           claw,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           elevator,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           backRight,     tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port5,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           liftLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           liftRight,     tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port8,           backLeft,      tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1)
	{
		if(vexRT[Btn5D])
		{
			motor[claw] = -127;
		}
		else if(vexRT[btn6D])
		{
			motor[claw] = 127;
		}
		else
		{
			motor[claw] = 20;
		}

		if(vexRT[Btn5U])
		{
			motor[liftLeft] = -85;
			motor[liftRight] = -85;
		}
		else if(vexRT[btn6U])
		{
			motor[liftLeft] = 85;
			motor[liftRight] = 85;
		}
		else
		{
			if(abs(nMotorEncoder[liftRight]) < 470)
			{
				motor[liftLeft] = 20;
				motor[liftRight] = 20;
			}
			else
			{
				motor[liftLeft] = -20;
				motor[liftRight] = -20;
			}
		}
		motor[frontRight] = motor[backRight] = vexRT[Ch2];
		motor[frontLeft] = motor[backLeft] = vexRT[Ch3];

	}
}
